// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["APP_DATABASE_DIRECT_URL"] || process.env["APP_DATABASE_URL"] || process.env["DATABASE_URL"] || process.env["POSTGRES_PRISMA_URL"],
  },
});
