"""v2 scripts after Barron's review (2026-10-04): holiday-gift hook, 1-second install (speed ramp), split-screen
comparisons, zoom-in callouts on every proof, life scenes (Christmas with kids, game day, date night, New Year's Eve).
Fields: t0/t1 · seg · eng (Kling | Veo | local | compare) · pic · cam · txt · vo · sfx · tr · hl (highlight/callout) ·
cmp (split-screen spec) · speed (time-remap factor) · kf / mo (prompts)."""

TV_DISCLAIMER = ("*Free standard professional installation with an eligible TV purchased on TCL.com, by TCL's authorized "
                 "third-party partner. Standard wall-mounting labor included; mount hardware and non-standard work extra. "
                 "Availability varies by location. Installation sped up for dramatization. Comparison images simulated.")

HOLIDAY_WORLD = "节日：圣诞树（暖白小灯）、壁炉上的袜子、窗外飘雪；无任何授权角色/品牌装饰。"

ADS = [
{
 "id": "QM7L-A", "title": "Unwrap the Holidays（拆开就是装好的）", "product": "TCL QM7L（Best Seller #1）", "event": "Black Friday · 节日送礼",
 "logline": "门铃一响，安装师傅抬进一个系着金色大蝴蝶结的“电视礼物”；1 秒装上墙，孩子撕开包装纸——屏幕直接亮起：惊喜是装好的。随后用分屏对比和放大镜证明 3,000 nits、Dolby Vision IQ、144Hz、2,100+ 分区，串起圣诞早晨、球赛日、跨年夜三个场景。",
 "cast": {"lock": "A Latino man in his late 30s, medium build, short dark wavy hair, neatly trimmed beard, warm brown skin with faint smile lines, wearing a forest-green knit holiday sweater over a white tee and dark jeans.",
          "others": "两个孩子（6 岁女孩、9 岁男孩，睡衣，只拍背影/侧脸/手）；安装师傅两人（红色针织帽、海军蓝工作服，背对镜头）；球赛日朋友 3 人（只在 S7 出现，侧面/群像）"},
 "world": "郊区客厅：大窗、橡木地板、米色沙发 + 格子毛毯、圣诞树（暖白灯）、壁炉与袜子、窗外雪；白天低角度冬日阳光（4000K），夜晚树灯 + 台灯（2700K）。" + HOLIDAY_WORLD,
 "screens": "自有屏幕画面：①雪中小镇的圣诞夜景（细节 + 高光）②卡丁车游戏画面（通用、无品牌）③通用橄榄球比赛（无联盟/球队标识）④城市天际线上空的跨年烟花（纯黑夜空）。",
 "refs": ["QM7L/QM7L_09.png", "QM7L/QM7L_04.png"],
 "price": '[黑五价 占位] · WAS $1,199.99（55"，以发布时官网 compare-at 为准）',
 "shots": [
  {"t0": 0.0, "t1": 1.0, "seg": "HOOK", "eng": "Kling", "tr": "片头：暗处冲入 + 雪粒子", "speed": 1,
   "pic": "雪夜门廊，门打开：两名戴红色针织帽的师傅抬着一个电视形状、包着红色礼品纸、系金色巨型蝴蝶结的大礼物进门；前景孩子背影惊呼",
   "cam": "whip → fast push-in", "txt": "BLACK FRIDAY SURPRISE（上三分之一，金色）", "vo": "This Black Friday, (0.2–1.0)",
   "sfx": "0.0 门铃 + 雪橇铃 whoosh", "hl": "金色蝴蝶结闪光 sparkle（本地粒子）", "cmp": None,
   "kf": "Medium-wide shot from inside the hallway, low angle, 24mm lens. The front door opens onto a snowy porch at dusk; two installers in red knit beanies and navy work jackets, faces turned away, carry a huge flat TV-shaped gift wrapped in glossy red paper with an oversized gold satin bow. A child in plaid pajamas, seen from behind, throws both arms up in the foreground. Snowflakes blow in, porch light warm, wet boot prints on the doormat.",
   "mo": "A fast whip from the stairs lands on the door, then a quick push-in. 0–1s: the installers step in tilting the gift through the frame, snow swirls in, the bow ribbons flutter, the child jumps in excitement; ends mid-jump."},
  {"t0": 1.0, "t1": 2.0, "seg": "HOOK", "eng": "Kling", "tr": "zoom punch + 安装咔哒", "speed": 4,
   "pic": "1 秒安装（4 倍速升速）：电钻 → 抬起 → 礼物（仍包着纸）咔哒扣上墙架",
   "cam": "arc 30°（升速）", "txt": "FREE PRO INSTALL*（下三分之一按钮）", "vo": "the surprise comes installed. (1.0–2.6)",
   "sfx": "电钻升调 + 2.0 click + impact", "hl": "画面右上角 1→2→3 安装进度三格小图标逐拍点亮", "cmp": None,
   "kf": "Medium shot, eye level, 35mm lens. In a living room with a lit Christmas tree, two installers in red beanies, seen from behind, lift the large gift-wrapped flat TV with its gold bow toward a wall bracket while one drives a screw with a cordless drill. Plaid throw on the sofa, stockings on the fireplace, warm afternoon window light.",
   "mo": "A smooth 30-degree arc around the wall over five seconds. The drill spins, both installers raise the wrapped TV, hook it onto the bracket with a firm push and step back, brushing their gloves; continuous natural-speed action (it will be sped up in the edit)."},
  {"t0": 2.0, "t1": 3.0, "seg": "HOOK", "eng": "Kling", "tr": "flash（屏幕点亮）", "speed": 1,
   "pic": "孩子一把撕开墙上电视的礼品纸，金色蝴蝶结朝镜头飞来，屏幕瞬间亮起雪中小镇",
   "cam": "push-in", "txt": "SURPRISE — IT'S INSTALLED", "vo": "",
   "sfx": "撕纸声 + 2.5 flash impact", "hl": "撕裂处金色光爆 burst（本地）", "cmp": None,
   "kf": "Medium close-up, low angle, 35mm lens. A nine-year-old boy in pajamas, seen in profile, grabs a strip of red gift paper on a wall-mounted TV and starts tearing it off; the gold bow is already flying toward the lens and a bright snowy-village picture glows through the tear. Christmas tree lights bokeh behind, torn paper edges catching warm light.",
   "mo": "A quick push-in. 0–1s: the boy rips the paper down in one big pull, it flutters away, the bow tumbles toward the camera, the screen's bright snowy village fills the frame; ends mid-tear motion."},
  {"t0": 3.0, "t1": 4.5, "seg": "BODY", "eng": "compare", "tr": "whip", "speed": 1,
   "pic": "上下分屏：上 = 旧电视在窗光直射下发灰（生成静帧 + 轻推）；下 = QM7L 同一画面通透明亮（视频）",
   "cam": "上：slow push；下：slow pull-out", "txt": "OLD TV / QM7L（分屏标签）· 3,000 NITS", "vo": "Three thousand nits beats the glare, (3.0–5.0)",
   "sfx": "impact", "hl": "放大镜：圈出下半屏的天空高光区域 1.6×，白色细环 + 标签 3,000 NITS", "cmp": "标签 OLD TV（深灰底）/ QM7L（品牌色底）；两半同机位同光线；小字 Simulated",
   "kf": "OURS: Medium shot, 35mm lens, slightly off-axis. Low winter sun from a large window falls directly across a wall-mounted TV showing a bright snowy village at dusk; the picture stays vivid with crisp highlights. Christmas tree on the right, plaid throw on the sofa arm in the foreground.  OTHER: the same room and framing with an older, thicker generic TV whose picture looks washed out and grey under the same direct sun.",
   "mo": "OURS: A slow pull-out from the screen. 0–1.5s: sunlight shifts across the screen as a curtain sways, the village lights twinkle, snow falls in the picture; ends mid-pull."},
  {"t0": 4.5, "t1": 6.0, "seg": "BODY", "eng": "Veo", "tr": "zoom punch", "speed": 1,
   "pic": "屏幕极近特写：雪花与窗灯的细节、Dolby Vision IQ 高光层次",
   "cam": "slow push into the screen", "txt": "DOLBY VISION IQ", "vo": "",
   "sfx": "shimmer", "hl": "放大镜：圈住窗灯与雪花，环形高亮 + 微光闪动", "cmp": None,
   "kf": "Extreme close-up on a wall-mounted TV screen, 85mm lens. The picture shows a snowy village street at night: warm lit windows, falling snowflakes and frost on a lamppost, rich detail in both the bright windows and the dark snow shadows. A sliver of the thin metal frame and a reflection-free surface at the edge of frame.",
   "mo": "A slow push toward the lit windows. 0–1.5s: snowflakes drift on screen, a window light flickers warmly, the push continues; ends mid-push."},
  {"t0": 6.0, "t1": 7.5, "seg": "BODY", "eng": "Kling", "tr": "flash（音乐 drop）", "speed": 1,
   "pic": "圣诞早晨：两个孩子穿睡衣、和爸爸一起在沙发上玩卡丁车游戏，身体跟着转弯倾斜，圣诞树灯闪",
   "cam": "handheld follow", "txt": "144HZ GAMING", "vo": "smooth one-forty-four for the kids, (6.0–7.8)",
   "sfx": "6.0 impact + 引擎声", "hl": "屏幕上速度线 speed lines 叠加 + 144Hz 标签弹出", "cmp": None,
   "kf": "Medium-wide shot, low angle, 28mm lens. Christmas morning: the same Latino man in a forest-green knit sweater sits between his two kids in plaid pajamas on a beige sofa, all three leaning hard to one side with game controllers, a kart race blurring across the wall-mounted TV. Torn wrapping paper on the floor, tree lights glowing, a mug of cocoa on the side table.",
   "mo": "Handheld follow that leans with them. 0–1s: all three lean into the turn, the little girl squeals and bumps her dad's shoulder. 1–1.5s: they lean the other way, dad laughs; ends mid-lean."},
  {"t0": 7.5, "t1": 9.0, "seg": "BODY", "eng": "Kling", "tr": "whip", "speed": 1,
   "pic": "球赛日：朋友们在沙发前跳起来庆祝达阵（通用橄榄球、无标识），零食碗翻飞",
   "cam": "crane down → push", "txt": "DOLBY ATMOS", "vo": "game-day roar with Dolby Atmos, (7.9–9.4)",
   "sfx": "观众欢呼 + 低频", "hl": "屏幕两侧声波环 pulse 扩散动画", "cmp": None,
   "kf": "Wide shot, low angle, 24mm lens. Game day in the same living room: the man in the green sweater and three friends leap up from the sofa cheering at a touchdown on the wall-mounted TV (generic football, no league or team logos); a bowl of popcorn flips in the air. Afternoon window light, holiday garland on the mantel.",
   "mo": "A crane down into a push-in. 0–1s: everyone jumps, arms up, popcorn sprays. 1–1.5s: two friends high-five; ends mid-high-five."},
  {"t0": 9.0, "t1": 10.5, "seg": "BODY", "eng": "Veo", "tr": "zoom punch", "speed": 1,
   "pic": "跨年夜：屏幕上城市天际线上空的烟花，周围纯黑夜空；一家人剪影倒数",
   "cam": "slow arc", "txt": "2,100+ ZONES", "vo": "and true black at midnight. (9.5–10.9)",
   "sfx": "烟花爆裂", "hl": "放大镜：圈住烟花边缘与旁边纯黑夜空，标签 2,100+ ZONES · TRUE BLACK", "cmp": None,
   "kf": "Wide shot from behind the sofa, 35mm lens. New Year's Eve: the family in silhouette, kids in paper party hats, watches fireworks burst over a generic city skyline on the wall-mounted TV, bright colors against deep true-black sky. Tree lights and a table lamp keep the room warmly readable; confetti on the sofa back.",
   "mo": "A slow arc from left to right. 0–1.5s: fireworks bloom on screen, the kids raise their arms for the countdown, confetti drifts; ends mid-arc."},
  {"t0": 10.5, "t1": 12.0, "seg": "BODY", "eng": "Kling", "tr": "whip（片尾前强转场）", "speed": 1,
   "pic": "一家人在沙发上拥抱碰杯（热可可），镜头升起展示整面墙：电视挂在圣诞树旁",
   "cam": "crane up / pull-out", "txt": "#1 BEST SELLER · INSTALLED FREE*", "vo": "",
   "sfx": "笑声 + whoosh", "hl": "#1 BEST SELLER 金色徽章盖章动画", "cmp": None,
   "kf": "Medium-wide shot, eye level, 28mm lens. The same Latino man in a green sweater hugs his two kids on the sofa, clinking mugs of cocoa, the wall-mounted TV glowing with a snowy village beside the Christmas tree. Warm tree lights, plaid throw, torn wrapping paper still on the rug.",
   "mo": "A crane up and gentle pull-out. 0–1s: mugs clink, the kids snuggle in. 1–1.5s: the camera rises to reveal the whole festive wall; ends while still rising."},
  {"t0": 12.0, "t1": 15.0, "seg": "CTA", "eng": "local", "tr": "whip + 13.0 click", "speed": 1,
   "pic": "片尾卡：QM7L 官方正面图（屏内合成雪中小镇）+ 金色蝴蝶结贴纸 + 飘雪粒子；13.5 切到侧面构图并标注 2.2\" 厚",
   "cam": "push → pull（两构图）", "txt": "[黑五价 占位] · WAS $1,199.99 · SHOP AT TCL.COM · 免责小字", "vo": "QM7L — installed free. Shop TCL.com. (12.2–14.4)",
   "sfx": "13.0 click + 铃铛", "hl": "价格牌弹入；侧面标注线 2.2\" SLIM", "cmp": None, "kf": "（本地合成）", "mo": "（本地合成）"},
 ],
},
{
 "id": "QM8L-A", "title": "Hangs Like Art（像画一样，一秒上墙）", "product": "TCL QM8L（Best Seller #2，旗舰）", "event": "Black Friday · 节日",
 "logline": "安装师傅上门，1 秒把 QM8L 像画框一样挂上墙；侧面 2.0 英寸的轻薄、上下分屏对比老电视；再用放大镜逐一证明 ZeroBorder、正午 6,000 nits、B&O 音效、烛光下 4,000+ 分区，串起球赛日与夫妻约会。",
 "cast": {"lock": "An East Asian woman in her early 40s, slim build, chin-length black bob with a few grey strands, light freckles across the nose, wearing an oatmeal linen shirt with rolled sleeves, a thin gold ring and small pearl studs.",
          "others": "丈夫（40 岁出头，深色毛衣，S7–S9 出现，以侧脸/背影为主）；安装师傅（炭灰工作服 + 针织帽，背对）；球赛日朋友（S6 群像）"},
 "world": "城市 loft：白色灰泥墙、整面落地窗、水泥地、胡桃木矮柜、两幅装裱画、绒面单椅；正午硬光；夜晚蜡烛 + 落地灯，窗外城市灯火与小雪。" + HOLIDAY_WORLD,
 "screens": "自有屏幕画面：①色块抽象画（画框模式）②正午体育场强光下的通用橄榄球（无标识）③沙漠星空明月（纯黑）④壁炉火焰（约会氛围）。",
 "refs": ["QM8L/QM8L_13.png", "QM8L/QM8L_15.png", "QM8L/QM8L_10.png（侧面）"],
 "price": '[黑五价 占位] · WAS $2,499.99（65"，以发布时官网 compare-at 为准）',
 "shots": [
  {"t0": 0.0, "t1": 1.0, "seg": "HOOK", "eng": "Kling", "tr": "片头：暗处冲入", "speed": 1,
   "pic": "门铃，门开：两名安装师傅抬着超薄的 QM8L 大步进门（窗外小雪）",
   "cam": "whip → handheld follow", "txt": "BLACK FRIDAY", "vo": "Black Friday: (0.2–0.9)",
   "sfx": "门铃 + whoosh", "hl": None, "cmp": None,
   "kf": "Medium-wide shot from inside a city loft, 24mm lens. The door opens; two installers in charcoal work jackets and knit beanies, faces turned away, stride in carrying a very large, remarkably thin flat-screen TV with its screen facing them. Light snow outside, concrete floor, white plaster wall, a framed print on the wall, hard cool daylight.",
   "mo": "A whip from the window lands on the door, then a handheld follow backward. 0–1s: the installers carry the thin panel in, it barely flexes, snowflakes swirl at the threshold; ends mid-stride."},
  {"t0": 1.0, "t1": 2.0, "seg": "HOOK", "eng": "Kling", "tr": "2.0 click + impact", "speed": 4,
   "pic": "1 秒安装（4 倍速）：两人把 QM8L 像挂画一样扣上墙，正好落在两幅装裱画之间",
   "cam": "orbit 40°（升速）", "txt": "FREE PRO INSTALL*", "vo": "the TV that hangs like art. (1.0–2.6)",
   "sfx": "升调 whoosh + 2.0 click", "hl": "落墙瞬间四角对齐线闪现（画框对齐框）", "cmp": None,
   "kf": "Medium shot, eye level, 35mm lens. Two installers in charcoal jackets, seen from behind, lift a large ultra-thin TV onto a wall bracket between two framed prints on a white plaster wall, like hanging a painting. Concrete floor, walnut credenza, bright window light from the left.",
   "mo": "A smooth 40-degree orbit over five seconds. They raise the thin TV, hook it on with a firm press, check it with a small level and step back; continuous natural-speed action (sped up in the edit)."},
  {"t0": 2.0, "t1": 3.0, "seg": "HOOK", "eng": "Veo", "tr": "zoom punch", "speed": 1,
   "pic": "侧面贴墙滑行：电视几乎贴平墙面，凸显轻薄",
   "cam": "lateral track along the wall", "txt": "2.0\" SLIM", "vo": "",
   "sfx": "shimmer", "hl": "侧面测量线：两端短横 + 2.0\" 标注（官网 65\" 机身厚度）", "cmp": None,
   "kf": "Side-profile close shot along a white plaster wall, 50mm lens, at the height of the TV. A very thin wall-mounted TV runs almost flush to the wall, its slim metal edge catching a line of window light, the screen glow spilling onto the plaster. Plaster texture and a faint shadow line behind the panel.",
   "mo": "A slow lateral track along the wall toward the TV's edge. 0–1s: the light line slides along the metal edge as the camera moves, the thin profile reads clearly; ends mid-track."},
  {"t0": 3.0, "t1": 4.5, "seg": "BODY", "eng": "compare", "tr": "whip", "speed": 1,
   "pic": "上下分屏：上 = 老式厚电视，宽黑边、画面发灰（生成静帧）；下 = QM8L 边到边的画框画面（视频）",
   "cam": "上：slow push；下：slow push to the corner", "txt": "OLD TV / QM8L · ZEROBORDER", "vo": "No border. No glare. (3.0–4.6)",
   "sfx": "impact", "hl": "放大镜：圈住 QM8L 角落，几乎看不见的边框，标签 ZEROBORDER", "cmp": "OLD TV（深灰）/ QM8L（品牌色）；同墙同光；小字 Simulated",
   "kf": "OURS: Close shot of a wall-mounted TV's top corner, 50mm lens: an abstract color-field painting in deep blue and terracotta runs right to the edge, the frame a hair-thin metal line against white plaster.  OTHER: the same wall and framing with an older, thick generic TV with a wide black bezel and a dull, washed-out picture.",
   "mo": "OURS: A slow push toward the corner. 0–1.5s: the painting's colors drift slowly as it pans, the thin edge glints; ends mid-push."},
  {"t0": 4.5, "t1": 6.0, "seg": "BODY", "eng": "Veo", "tr": "flash", "speed": 1,
   "pic": "正午球赛日：落地窗阳光直射屏幕，体育场强光下的橄榄球画面依然通透",
   "cam": "pull-out", "txt": "6,000 NITS", "vo": "Six thousand nits at noon, (4.7–6.2)",
   "sfx": "体育场环境声", "hl": "放大镜：圈住体育场灯塔高光，标签 6,000 NITS", "cmp": None,
   "kf": "Wide shot, eye level, 28mm lens. Noon sun pours through floor-to-ceiling windows directly onto a wall-mounted TV showing a generic football game under bright stadium floodlights (no league or team logos); the picture stays punchy and crisp. Window-mullion shadows stripe the concrete floor, snacks on the walnut credenza.",
   "mo": "A steady pull-out from the screen. 0–1.5s: the camera glides back, the shadows of the window mullions slide across the floor, the players sprint on screen; ends while still pulling back."},
  {"t0": 6.0, "t1": 7.5, "seg": "BODY", "eng": "Kling", "tr": "flash（drop）", "speed": 1,
   "pic": "朋友们在阳光 loft 里为达阵跳起击掌",
   "cam": "handheld follow", "txt": "4K 144HZ", "vo": "",
   "sfx": "6.0 impact + 欢呼", "hl": None, "cmp": None,
   "kf": "Medium-wide shot, low angle, 24mm lens. In the sunlit loft the same East Asian woman with a black bob and three friends jump up from a low sofa cheering a touchdown on the wall-mounted TV; two friends mid high-five. Hard noon light, linen and denim creases, a snack bowl tipping.",
   "mo": "Handheld follow. 0–1s: everyone leaps up, arms raised, the bowl tips. 1–1.5s: the high-five lands and they laugh; ends mid-celebration."},
  {"t0": 7.5, "t1": 9.0, "seg": "BODY", "eng": "Kling", "tr": "whip（日→夜）", "speed": 1,
   "pic": "傍晚约会：丈夫点燃矮柜上的蜡烛，妻子端两杯红酒走来，音乐从电视铺开",
   "cam": "slow arc", "txt": "SOUND BY B&O", "vo": "sound by Bang & Olufsen, (7.6–9.1)",
   "sfx": "火柴声 + 低频铺底", "hl": "电视两侧声波环扩散动画", "cmp": None,
   "kf": "Medium shot, eye level, 35mm lens. Evening in the loft: a man in a dark wool sweater, in profile, lights candles on the walnut credenza under the wall-mounted TV showing a crackling fireplace, while the same East Asian woman in an oatmeal linen shirt walks in with two glasses of red wine. City lights and light snow through the windows, warm candle glow on their faces.",
   "mo": "A slow arc from right to left. 0–1s: the match flares and the candle catches, she steps in holding the glasses. 1–1.5s: he turns to take a glass; ends mid-reach."},
  {"t0": 9.0, "t1": 10.5, "seg": "BODY", "eng": "Veo", "tr": "zoom punch", "speed": 1,
   "pic": "烛光电影夜：屏幕上沙漠星空与明月，月亮四周纯黑；情侣依偎在单椅里",
   "cam": "slow push", "txt": "4,000+ ZONES", "vo": "and true black by candlelight. (9.3–10.8)",
   "sfx": "低频 swell", "hl": "放大镜：圈住月亮边缘与纯黑夜空，标签 4,000+ ZONES · TRUE BLACK", "cmp": None,
   "kf": "Wide shot, low angle, 35mm lens. Candles and a floor lamp warm the loft while the wall-mounted TV shows a bright moon over a desert star field with deep true-black sky; the couple sits close in a boucle loveseat, faces and furniture readable. Snow drifting past the dark windows.",
   "mo": "A slow push toward the screen. 0–1.5s: candle flames flicker, she rests her head on his shoulder, stars glint on screen; ends mid-push."},
  {"t0": 10.5, "t1": 12.0, "seg": "BODY", "eng": "Kling", "tr": "whip（片尾前）", "speed": 1,
   "pic": "两人碰杯，镜头升起：电视与两幅装裱画组成一面画廊墙",
   "cam": "crane up", "txt": "INSTALLED FREE*", "vo": "",
   "sfx": "碰杯 + whoosh", "hl": None, "cmp": None,
   "kf": "Medium-wide shot, eye level, 28mm lens. The couple clinks wine glasses on the loveseat; behind them the borderless TV, showing an abstract color-field painting, hangs between two framed prints like part of a gallery wall. Candlelight, city lights through tall windows, a throw over the armrest.",
   "mo": "A gentle crane up. 0–1s: the glasses clink, she laughs. 1–1.5s: the camera rises to reveal the gallery wall; ends while still rising."},
  {"t0": 12.0, "t1": 15.0, "seg": "CTA", "eng": "local", "tr": "whip + 13.0 click", "speed": 1,
   "pic": "片尾卡：QM8L 正面（屏内抽象画）→ 13.5 侧面构图 + 2.0\" 标注线；价格、CTA、免责",
   "cam": "push → pull", "txt": "[黑五价 占位] · WAS $2,499.99 · SHOP AT TCL.COM · 免责小字", "vo": "Installed free. Shop TCL.com. (12.2–14.0)",
   "sfx": "13.0 click", "hl": "价格牌弹入；2.0\" SLIM 标注", "cmp": None, "kf": "（本地合成）", "mo": "（本地合成）"},
 ],
},
{
 "id": "NXT-A", "title": "Full Page, No Glare（整页乐谱，节日版）", "product": "TCL NXTPAPER 14", "event": "Black Friday · 节日送礼",
 "logline": "雪天的窗边，风吹散纸质乐谱 → NXTPAPER 14 放上谱架；分屏对比普通亮面平板的反光；放大镜证明整页 A4、笔翻页、一键墨水纸；最后是拆礼物、教弟弟弹《Silent Night》。",
 "cast": {"lock": "A Black woman in her early 20s, slender build, natural curly hair tied up with a few loose curls framing her face, deep brown skin with a small mole above her lip, wearing a rust-brown cable-knit cardigan over a cream tee and small silver hoop earrings.",
          "others": "弟弟（约 10 岁，S10，侧面/背影）"},
 "world": "家中钢琴角：旧立式钢琴、磨损的象牙色琴键、节拍器与铅笔、窗外飘雪、角落一棵小圣诞树；白天窗光，晚上黄铜台灯。",
 "screens": "屏内乐谱：本地排版公有领域《Silent Night》（Gruber, 1818），彩色纸与墨水纸两版；含屏幕特写的镜头一律本地合成。",
 "refs": ["NXTPAPER14/NXTPAPER14_10.png（侧面）", "NXTPAPER14/NXTPAPER14_01.png（正面 + 笔；屏幕替换为乐谱）"],
 "price": "[黑五价 占位] · WAS $469.99（以发布时官网 compare-at 为准）",
 "shots": [
  {"t0": 0.0, "t1": 1.0, "seg": "HOOK", "eng": "Kling", "tr": "片头：暗处冲入 + 风声", "speed": 1,
   "pic": "窗被风吹开，雪花和纸质乐谱一起在空中翻飞，她伸手去抓", "cam": "whip → fast push-in", "txt": "STILL USING PAPER?", "vo": "Pages flying again? (0.2–1.2)",
   "sfx": "风 + 纸张", "hl": None, "cmp": None,
   "kf": "Medium shot, eye level, 35mm lens. A gust throws open the window beside a worn upright piano; sheets of printed sheet music and a few snowflakes swirl off the music stand while the same young Black woman with tied-up curls in a rust cable-knit cardigan reaches up to catch them, mid-motion. A small Christmas tree in the corner, cold daylight, pencil and metronome on the lid.",
   "mo": "A whip that lands on the piano, then a fast push-in. 0–1s: pages and snowflakes spin through the air, she lunges and catches one, curls bouncing; ends mid-catch."},
  {"t0": 1.0, "t1": 2.0, "seg": "HOOK", "eng": "Veo", "tr": "whip", "speed": 1,
   "pic": "她把 NXTPAPER 14 放上谱架，窗光正照屏幕", "cam": "push-in", "txt": "NXTPAPER 14", "vo": "Next Paper Fourteen (1.3–2.2)",
   "sfx": "轻放声", "hl": None, "cmp": None,
   "kf": "Medium close-up, eye level, 50mm lens. Hands set a large slim grey tablet showing a full page of sheet music on the music stand of an upright piano; snowy daylight from the window falls straight across its matte screen with no glare spot. Worn ivory keys in the foreground, cardigan sleeve with loose knit.",
   "mo": "A steady push-in. 0–1s: the hands let go and the tablet settles against the stand, window light sweeps across the matte surface; ends mid-push."},
  {"t0": 2.0, "t1": 3.5, "seg": "HOOK", "eng": "compare", "tr": "zoom punch", "speed": 1,
   "pic": "上下分屏：上 = 普通亮面平板，屏幕中央一块白色反光（生成静帧）；下 = NXTPAPER 14 乐谱清晰（本地合成 + 光带扫过）",
   "cam": "上：slow push；下：light sweep", "txt": "GLOSSY TABLET / NXTPAPER 14 · NO GLARE", "vo": "shows the whole page — no glare. (2.2–3.8)",
   "sfx": "shimmer", "hl": "放大镜：圈住下半屏的音符，1.8× 清晰放大，标签 NO GLARE", "cmp": "GLOSSY TABLET（深灰）/ NXTPAPER 14（品牌色）；同谱架同光线；小字 Simulated",
   "kf": "OTHER: the same piano music stand and window light with a generic glossy tablet showing sheet music, a bright white window reflection washing out the middle of the screen.  OURS: local composite — the official NXTPAPER 14 front image with our typeset sheet music and a warm light sweep.",
   "mo": "（本地合成 + 静帧推镜）"},
  {"t0": 3.5, "t1": 5.0, "seg": "BODY", "eng": "local", "tr": "cut on beat", "speed": 1,
   "pic": "屏幕正面特写（本地合成）：A4 纸框描边动画套在屏幕上，显示整页刚好放下", "cam": "slow push", "txt": "FULL A4 PAGE · 14.3\"", "vo": "",
   "sfx": "纸张轻响", "hl": "A4 纸框描边线条动画 + 14.3\" 标签", "cmp": None, "kf": "（本地合成）", "mo": "（本地合成）"},
  {"t0": 5.0, "t1": 6.5, "seg": "BODY", "eng": "Kling", "tr": "whip", "speed": 1,
   "pic": "她弹奏，右手抬起用 T-Pen 轻点屏幕翻页", "cam": "track left", "txt": "T-PEN PAGE TURN", "vo": "Tap to turn the page, (5.1–6.4)",
   "sfx": "钢琴 + 笔尖轻点", "hl": "笔尖触点处光圈 ripple", "cmp": None,
   "kf": "Close-up from the side, 35mm lens. The same young Black woman in a rust cardigan plays the upright piano, fingers mid-chord on worn ivory keys, as her right hand lifts a slim stylus toward the tablet on the music stand. Snow outside the window, small silver hoop catching light, tree lights bokeh behind.",
   "mo": "A smooth track to the left along the keyboard. 0–1s: her fingers run a quick phrase. 1–1.5s: she taps the tablet with the stylus to turn the page and drops back onto the keys; ends mid-phrase."},
  {"t0": 6.5, "t1": 7.5, "seg": "BODY", "eng": "Veo", "tr": "flash（drop）", "speed": 1,
   "pic": "拇指按下侧边 NXTPAPER 键", "cam": "push-in", "txt": "ONE KEY", "vo": "one key for ink paper, (6.5–7.8)",
   "sfx": "按键 click + impact", "hl": "放大镜：圈住侧边按键，环形高亮", "cmp": None,
   "kf": "Extreme close-up, 85mm lens. A thumb presses a small physical key on the edge of a slim grey tablet resting on a piano music stand; a strip of sheet music on the matte screen and the cardigan cuff visible. Warm side light, fine dust on the stand.",
   "mo": "A slow push-in. 0–1s: the thumb presses the key firmly and releases; ends on the release."},
  {"t0": 7.5, "t1": 8.5, "seg": "BODY", "eng": "local", "tr": "wipe（彩色 → 墨水纸）", "speed": 1,
   "pic": "本地合成：乐谱屏幕从彩色纸模式向下擦除切换成墨水纸模式", "cam": "static-drift", "txt": "INK PAPER MODE", "vo": "",
   "sfx": "纸张翻动", "hl": "擦除线 + 模式标签", "cmp": None, "kf": "（本地合成）", "mo": "（本地合成）"},
  {"t0": 8.5, "t1": 10.0, "seg": "BODY", "eng": "Kling", "tr": "whip", "speed": 1,
   "pic": "夜晚台灯下仍在练琴，伸展肩膀、微笑、继续弹", "cam": "slow arc", "txt": "EASY ON THE EYES", "vo": "and practice for hours. (8.6–9.9)",
   "sfx": "钢琴延续", "hl": None, "cmp": None,
   "kf": "Medium shot, eye level, 35mm lens. Evening at the same upright piano: a warm brass desk lamp lights the same young Black woman in a rust cardigan as she rolls her shoulders mid-stretch, the tablet on the stand showing soft grey ink-paper sheet music. Window deep blue with falling snow, tree lights in the corner.",
   "mo": "A slow arc. 0–1s: she stretches and smiles at the page. 1–1.5s: she places her hands back on the keys and starts playing; ends mid-phrase."},
  {"t0": 10.0, "t1": 11.0, "seg": "BODY", "eng": "Veo", "tr": "zoom punch", "speed": 1,
   "pic": "礼物时刻：牛皮纸礼盒（无字）抽开红丝带，取出平板", "cam": "crane down", "txt": "GIFT IT", "vo": "",
   "sfx": "丝带 + 纸张", "hl": "丝带抽开时金色闪光", "cmp": None,
   "kf": "Top-down shot, 35mm lens. On a wooden table under a small Christmas tree, hands pull a red ribbon off a plain kraft-paper gift box with no printing; the lid lifts to reveal a slim grey tablet. Wrapping scraps, a spool of ribbon, pine needles, warm window light.",
   "mo": "A slow crane down. 0–1s: the ribbon slides loose and the lid lifts; ends mid-lift."},
  {"t0": 11.0, "t1": 12.0, "seg": "BODY", "eng": "Kling", "tr": "whip（片尾前）", "speed": 1,
   "pic": "她把平板放在弟弟面前，弟弟按下《Silent Night》第一个音，两人笑", "cam": "handheld follow", "txt": "NOTHING TO SET UP", "vo": "Nothing to set up — just play. (10.4–12.2)",
   "sfx": "单音琴声 + 笑声", "hl": None, "cmp": None,
   "kf": "Medium shot, eye level, 35mm lens. The same young Black woman in a rust cardigan leans over her ten-year-old brother, seen in profile, at the upright piano and sets the tablet with sheet music on the stand. Snowy afternoon light, his small hands hovering over worn keys, her hand on his shoulder, tree lights behind.",
   "mo": "A handheld follow that leans in. 0–1s: she slides the tablet onto the stand and points at the first note; he presses a key and both laugh; ends mid-laugh."},
  {"t0": 12.0, "t1": 15.0, "seg": "CTA", "eng": "local", "tr": "whip + 13.0 click", "speed": 1,
   "pic": "片尾卡：NXTPAPER 14 正面（屏内乐谱）+ 礼物丝带 → 13.5 侧面 6.95 mm 标注", "cam": "push → pull", "txt": "[黑五价 占位] · WAS $469.99 · SHOP AT TCL.COM", "vo": "Black Friday at TCL.com. (12.4–14.0)",
   "sfx": "13.0 click + 铃铛", "hl": "价格牌弹入；6.95 mm 标注线", "cmp": None, "kf": "（本地合成）", "mo": "（本地合成）"},
 ],
},
]

COST = {"Kling": 0.42, "Veo": 0.12, "compare": 0.14, "local": 0.0}

if __name__ == "__main__":
    import json, os
    here = os.path.dirname(os.path.abspath(__file__))
    json.dump({"ads": ADS, "tv_disclaimer": TV_DISCLAIMER}, open(f"{here}/scripts_v2.json", "w"), ensure_ascii=False, indent=1)
    for a in ADS:
        vo = " ".join(s["vo"].split(" (")[0] for s in a["shots"] if s["vo"])
        n = len(vo.split()); gen = [s for s in a["shots"] if s["eng"] != "local"]
        cost = sum(COST[s["eng"]] for s in a["shots"]) + 0.018 * (len(gen) + 2)
        hl = sum(1 for s in a["shots"] if s.get("hl")); cmp = sum(1 for s in a["shots"] if s.get("cmp"))
        over = [s for s in a["shots"] if s["t1"] - s["t0"] > 2.0 and s["seg"] != "CTA"]
        hook_install = any(s["seg"] == "HOOK" and "INSTALL" in s["txt"].upper() for s in a["shots"])
        print(f"{a['id']}: {len(a['shots'])} shots · {sum(1 for s in gen if s['eng']=='Kling')} Kling · {hl} highlights · {cmp} split-compare · install in hook: {hook_install} · VO {n} w ({n/15:.1f} w/s) · est ${cost:.2f} · >2s: {len(over)}")
        print("   ", vo)
