/* eslint-disable */
// GENERATED by scripts from out/research/ad-research (2026-10-06). Edit the research, then regenerate.
import type { HookDef } from "./types";

export const HOOK_DATA: Omit<HookDef, "family" | "frameOneProduct">[] = [
 {
  "id": "H01",
  "name": "Hero Turntable Reveal (360° spin)",
  "desc": "the product turns on a seamless sweep or podium, already lit, and a spec lands on beat 2.",
  "categories": "consumer electronics, small appliances, footwear, bottles and packaging, car accessories.",
  "platforms": "Meta Reels and Feed (premium look), Shorts. On TikTok, pair it with `T-NATIVE` text.",
  "emotion": "desire, premium appraisal.",
  "keyframe": "official packshot cut out at a 3/4 angle on a gradient plate. The product fills 55–65% of frame width, centred at y 650–1150.",
  "motion": "2.5D yaw built from 2–3 official angles crossfaded on beats, plus a 1.00→1.08 push. AI alternative: image-to-video \"locked camera, slow 360° turntable, soft rim light\".",
  "durationSec": [
   1.5,
   2.0
  ],
  "text": "`T-STACK` (name or benefit, then the spec on beat 2)",
  "sfx": "`riser`→`thump` on the spec.",
  "risk": "AI invents the unseen back side (mirrored logos, moved ports) and warps on-product text. Use only angles you own.",
  "aiFit": "high",
  "perf": "[A, principle-level] Showing the product more than once gave 2.7× odds of top-20% purchase intent, and product plus USPs gave 5.3× [S3]. TikTok catalog ads with product-focused video had 56% higher ROAS than brand-focused video [S6]."
 },
 {
  "id": "H02",
  "name": "Macro Detail Pull-Back",
  "desc": "open on an extreme macro of a texture, stitch, nozzle or screen pixel, then pull back to reveal the whole product.",
  "categories": "jewellery, skincare textures, knives and cookware, TVs and monitors (pixel macro), fabrics.",
  "platforms": "Reels, TikTok, Shorts.",
  "emotion": "curiosity (\"what is this?\"), then appreciation.",
  "keyframe": "macro crop of the official hi-res photo at 6–8× zoom on a feature detail.",
  "motion": "`zoompan` from z=6 to z=1 with ease-out over 1.2 s, plus a slight rotation (±3°) for life. AI option: \"macro lens, shallow depth of field, slow dolly out\".",
  "durationSec": [
   1.2,
   1.8
  ],
  "text": ": a single word on the macro (\"Real 925 silver.\"), then `T-STACK` after the reveal",
  "sfx": "`whoosh` on the pull-back plus a `chime` sparkle.",
  "risk": "upscaling artefacts at 8× (source photos need ≥ 3000 px). AI macro \"texture hallucination\" changes the material.",
  "aiFit": "high",
  "perf": "[B] Slow motion and macro detail are listed among the reliable \"visual hooks\" for texture-led categories [S17]. [A] Curiosity and suspense openers gave +16% watch time [S1]."
 },
 {
  "id": "H03",
  "name": "Light-Sweep / Specular Glint Reveal",
  "desc": "a light bar sweeps across the product and makes a glint, as in a premium launch film.",
  "categories": "electronics, watches and jewellery, cars and car tech, premium appliances.",
  "platforms": "Meta, Shorts. Too polished for cold TikTok unless the next shot is lo-fi.",
  "emotion": "awe, premium cue.",
  "keyframe": "product on a dark-graded but **not black** plate. Keep the product mid-tone bright so frame 1 is legible.",
  "motion": "overlay a rotated white gradient bar (additive blend, 30% opacity) moving x −600→+1700 in 0.7 s, plus a lens-flare PNG on the edge highlight and a 1.00→1.05 push.",
  "durationSec": [
   1.0,
   1.5
  ],
  "text": ": the logo or model name fades in after the sweep",
  "sfx": "`whoosh` matched to the bar, then a high `chime`.",
  "risk": "a dark open breaks the frame-1-bright rule, so start at ≥ 40% luminance. It reads as a TV spot, and TikTok says TikTok-first ads drove 3.3× actions versus non-TikTok-first ads [S1].",
  "aiFit": "high",
  "perf": "[C] A premium-launch convention. Use it as the brand variant, and A/B it against H04 for DR."
 },
 {
  "id": "H04",
  "name": "Product Blast (push to lens)",
  "desc": "on frame 1 the product rushes at the camera, bright, and spec lines stack in. This is the existing `--hook p`.",
  "categories": "everything, best for retargeting and promotions.",
  "platforms": "all.",
  "emotion": "energy, immediacy.",
  "keyframe": "product cutout at 40% scale on a brand-colour plate.",
  "motion": "scale 0.4→1.15→1.0 (back-out) in 0.35 s, motion blur, then a 6 px camera shake decaying over 0.2 s.",
  "durationSec": [
   0.8,
   1.5
  ],
  "text": ": 2–3 spec lines `T-POP` on consecutive beats",
  "sfx": "`whoosh`→`thump`.",
  "risk": "low. It can feel like a banner ad to cold audiences.",
  "aiFit": "high",
  "perf": "[A, principle-level] Brand or product early gave 1.7× [S3], and TikTok calls early product placement good for memorability [S1]. In the skill's own record it is the best retargeting variant."
 },
 {
  "id": "H05",
  "name": "Unboxing / Lid-Lift",
  "desc": "hands open a box, lift the lid or peel the film, and the product is revealed in its packaging.",
  "categories": "electronics, beauty sets, subscription boxes, toys, premium packaging.",
  "platforms": "TikTok, Reels.",
  "emotion": "anticipation, then reward.",
  "keyframe": "top-down box on a table, hands already gripping the lid (a mid-motion keyframe).",
  "motion": "AI image-to-video \"hands lift the lid in one motion, tissue parts, product revealed\" for 1.5 s. Cut on the reveal to the official packshot composited into the box.",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "`T-NATIVE` \"Unboxing the ___ everyone's talking about\"",
  "sfx": "`rip` or tape, cardboard `foley`, then `chime`.",
  "risk": "AI hands (finger count, merging), and the packaging art does not match the real box. Use the official box photo as the keyframe.",
  "aiFit": "med",
  "perf": "[A] 28% of TikTok holiday shoppers engage with unboxings, and 25% with product close-ups [S6]. [B] UGC unboxing is called one of the highest-trust TikTok formats [S29][S32]."
 },
 {
  "id": "H06",
  "name": "Gift Reveal (wrap tear / bow pull)",
  "desc": "a wrapped gift is torn or a bow is pulled, and the product appears.",
  "categories": "gifts of any kind, jewellery, gadgets, beauty sets, toys.",
  "platforms": "TikTok, Reels in Q4 and around Valentine's and Mother's Day.",
  "emotion": "surprise, delight, nostalgia.",
  "keyframe": "a gift box with a bow, mid-pull.",
  "motion": "AI \"ribbon pulled, paper torn open\" for 1.2 s, then a match-cut to the hero packshot (H04 push), with confetti particles.",
  "durationSec": [
   1.5,
   2.0
  ],
  "text": "`T-STACK` \"The gift they'll actually use 🎁\"",
  "sfx": "`rip`, then `pop` and a sleigh-bell `chime` in Q4.",
  "risk": "paper physics morphing, and the reveal must show the real SKU.",
  "aiFit": "med",
  "perf": "[A] Opening on surprise gave a 1.7× view-through rate [S1]. 25% of TikTok users are more likely than average to buy gifts online [S6]. The TCL BF retrospective already moved to a gift reveal in the 0–3 s window."
 },
 {
  "id": "H07",
  "name": "Extreme Reaction Close-Up",
  "desc": "a tight face shot of a jaw-drop, wide eyes or a hand over the mouth, before the cause is shown.",
  "categories": "novelty gadgets, beauty results, food, deals.",
  "platforms": "TikTok, Reels.",
  "emotion": "surprise, contagious emotion.",
  "keyframe": "a face filling 60% of the frame, mid-expression (mouth opening), centred in the BODY_BAND.",
  "motion": "a fast 1.0→1.12 punch-in on the peak expression, then a whip-pan to the product.",
  "durationSec": [
   0.8,
   1.2
  ],
  "text": "`T-NATIVE` \"I wasn't ready for this 😳\"",
  "sfx": "`scratch` or a gasp `foley`.",
  "risk": "**high**. AI faces morph, teeth and eyes glitch, and the uncanny valley hurts trust. Prefer a real creator clip, or keep the AI face ≤ 1 s with the face never moving its mouth. It also needs the AIGC label [S8].",
  "aiFit": "low",
  "perf": "[A] Opening on powerful emotions such as surprise gave a 1.7× 6-s view rate versus neutral expressions [S1][S16]."
 },
 {
  "id": "H08",
  "name": "POV Hook",
  "desc": "a first-person shot with \"POV: you finally found a ___ that ___\" as text.",
  "categories": "home, kitchen, car tech, cycling and outdoor, apps.",
  "platforms": "TikTok first, then Reels.",
  "emotion": "identification (\"that's me\").",
  "keyframe": "a first-person view with hands holding or using the product in a real setting (car dash, kitchen counter).",
  "motion": "handheld micro-shake (±4 px at 1–2 Hz), a natural walk-in.",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "`T-NATIVE` top band \"POV: …\"",
  "sfx": ": ambient room tone plus trending-style music.",
  "risk": "hands, so frame the product dominant and keep the hands partial. It must not look like stock footage.",
  "aiFit": "med",
  "perf": "[B] POV product discovery is listed among top TikTok ad formats [S29]. [A] TikTok-first, lo-fi ads gave 3.3× actions [S1]."
 },
 {
  "id": "H09",
  "name": "Problem → Instant Fix",
  "desc": "0.8 s of the pain (a mess, failure or frustration), then the product fixes it on the cut.",
  "categories": "cleaning, home, kitchen, car (phone mount falling), cable tidies, skincare (shine), pet.",
  "platforms": "all, strongest on TikTok and Reels for cold audiences.",
  "emotion": "frustration, then relief.",
  "keyframe": "the problem state, exaggerated (smoke, a tangle, a cracked screen). KF B: the solved state.",
  "motion": "KF A shakes slightly (frustration), then a `whoosh` whip transition to KF B with the product in use.",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": ": A gets \"Tired of ___?\" (red X emoji) and B gets \"Fixed in 3 seconds.\"",
  "sfx": ": a sigh or fail sound, then `whoosh`, then `chime`.",
  "risk": "problem exaggeration can be judged an \"exaggerated result\" claim [S8]. Keep the fix realistic.",
  "aiFit": "high",
  "perf": "[B] Problem-first is strongest for cold, problem-aware audiences, and demonstration is strongest for physical products [S16]. [A] TikTok lists problem-solution as a recommended narrative structure [S1]."
 },
 {
  "id": "H10",
  "name": "Before / After Split",
  "desc": "a split screen or wipe shows the dull or old state against the vivid new state. This is the existing `--hook c` (small, boxed \"before\" bursts full-bleed).",
  "categories": "TVs and displays, cleaning, home makeovers, organisation, lighting, cameras (stabilised versus shaky).",
  "platforms": "all.",
  "emotion": "contrast, aspiration.",
  "keyframe": "two frames from the same camera position. \"Before\" is desaturated (`eq=saturation=0.4`) and \"after\" is vivid.",
  "motion": "a vertical wipe line sweeps x 0→1080 in 0.6 s, or the boxed \"before\" explodes full-bleed on beat 2.",
  "durationSec": [
   1.2,
   2.0
  ],
  "text": ": \"BEFORE\" and \"AFTER\" labels at 40 px at the top of each side, plus the claim in `T-STACK`",
  "sfx": "`whoosh` on the wipe. - Risk, **policy**: - TikTok disallows before/after comparisons that create a false or distorted impression without evidence or a disclaimer [S8]. - Meta prohibits weight-loss before/after imagery and ads that create negative self-perception [S10]. Reports say the July 2026 health-ads rewrite moved Meta from auto-rejection to claim-by-claim review; treat this as unverified [S10b]. - **Never use it for weight loss, body or skin results without substantiation.** Fine for TVs, cleaning and home.",
  "risk": "",
  "aiFit": "high",
  "perf": "[B] Transformation hooks work well in beauty, fitness, home and productivity [S16]. Search summary of the agrowth guide."
 },
 {
  "id": "H11",
  "name": "Satisfying / ASMR Texture",
  "desc": "close, tactile action with crisp foley: a click, pour, sizzle, peel or crunch.",
  "categories": "food and kitchen appliances (air fryer crunch), beauty textures, stationery, mechanical gadgets, cleaning.",
  "platforms": "TikTok, Reels (sound-on).",
  "emotion": "sensory pleasure, calm.",
  "keyframe": "macro of the action (basket sliding out, a cream swirl, a magnet snapping).",
  "motion": "slow motion at 0.5× via `setpts=2*PTS` with frame interpolation (`minterpolate=fps=60`) or an AI-generated slow-motion clip.",
  "durationSec": [
   1.5,
   3.0
  ],
  "text": ": minimal, one word or none. Let the sound carry it",
  "sfx": ": high-quality `foley` mixed −6 dB above the music.",
  "risk": "liquids and food physics often go wrong in AI (viscosity, splashes that merge). Synthetic foley can sound fake, so layer real samples.",
  "aiFit": "med",
  "perf": "[A] TikTok recommends sounds that amplify actions \"for ASMR, demonstrations\" [S1]. [B] Academic results are mixed: ASMR engagement mediates purchase intent in some studies, and a non-ASMR ad outperformed in others [S25]. **A/B it. Do not assume it wins.**"
 },
 {
  "id": "H12",
  "name": "Speed-Ramp Transformation",
  "desc": "real speed, a ramp to 4–8× through a transformation (assembly, cooking, room clean-up), then a snap back to real speed at the result.",
  "categories": "furniture, kitchen (cook cycle), cleaning robots, DIY, cycling gear set-up.",
  "platforms": "TikTok, Reels, Shorts.",
  "emotion": "momentum, satisfaction.",
  "keyframe": "the start state. The clip (≥ 4 s generated) is compressed by a piecewise `setpts` (1×→0.15×→1×) with motion blur (`tmix=frames=4`) during the ramp. - DUR 1.5–2.5 s. TXT: a timer counter `T-BADGE` (\"12 min → 2 s\"). SFX `riser` during the ramp and a `thump` on the land.",
  "motion": "",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": ": a timer counter `T-BADGE` (\"12 min → 2 s\")",
  "sfx": "`riser` during the ramp and a `thump` on the land.",
  "risk": "AI continuity across the transformation, where objects pop in and out. Generate start and end keyframes and use first- and last-frame conditioning.",
  "aiFit": "med",
  "perf": "[C] A standard TikTok transition grammar. [A] Fast scene changes \"draw users in early\" [S1]. ### Text- and claim-led family"
 },
 {
  "id": "H13",
  "name": "\"3 Reasons\" Listicle",
  "desc": "\"3 reasons I switched to ___\" with a numbered badge, each reason shown as a 1–2 s proof shot.",
  "categories": "all, best for considered purchases (electronics, appliances, apps).",
  "platforms": "TikTok, Reels, Shorts.",
  "emotion": "curiosity plus a promise of efficiency.",
  "keyframe": "the hero product with a `T-BADGE` \"1\" slot.",
  "motion": "the badge counter flips 1→2→3 on beats, and each beat cuts to a proof clip.",
  "durationSec": [
   1.0,
   2.0
  ],
  "text": "`T-STACK` \"3 reasons this ___ sold out\" plus a `T-BADGE`",
  "sfx": "`click` per number.",
  "risk": "low. The reasons must be visual proofs, not text slides (slideshow risk, see lessons #6).",
  "aiFit": "high",
  "perf": "[B] The listicle or feature breakdown is a standard UGC ad format [S29]. [A] Product plus USPs gave 5.3× [S3]."
 },
 {
  "id": "H14",
  "name": "Question Text Hook",
  "desc": "an on-screen question over live footage, with line 2 landing on beat 2. This is the existing `--hook q`.",
  "categories": "all, best for problem-aware audiences.",
  "platforms": "all.",
  "emotion": "a forced mental yes/no.",
  "keyframe": "live product-in-use footage (never a blank card).",
  "motion": "slow push, 1.00→1.06.",
  "durationSec": [
   1.0,
   2.0
  ],
  "text": "`T-STACK`: \"Still using a ___ from 2015?\" then \"Watch this.\"",
  "sfx": ": a soft `pop` per line.",
  "risk": "weak for unaware audiences [S16]. The question must be answered before 5 s.",
  "aiFit": "high",
  "perf": "[B] A direct-address question forces a mental yes/no and suits problem-aware audiences [S16]."
 },
 {
  "id": "H15",
  "name": "Shock Stat / Bold Number",
  "desc": "a huge number fills the frame (\"98 inches\", \"10× brighter\", \"1,000,000 sold\") over the product.",
  "categories": "electronics (spec-led), best-sellers, apps.",
  "platforms": "Meta, Shorts, TikTok.",
  "emotion": "surprise, credibility.",
  "keyframe": "the product behind a semi-transparent 320–420 px numeral.",
  "motion": "the numeral counts up (rolling digits) in 0.6 s, then slams with a 1.15→1.0 scale and shake.",
  "durationSec": [
   1.0,
   1.5
  ],
  "text": "`T-BADGE` plus a qualifier line (\"…and it fits on your wall\")",
  "sfx": ": rolling `click`s, then a `thump`.",
  "risk": "the claim must be substantiated and match the landing page. Absolute claims draw ad-review scrutiny [S8][S16].",
  "aiFit": "high",
  "perf": "[B] Bold and specific statements, and social-proof numbers, are listed hook types [S16]. Social proof performs better mid-funnel than cold [S16]."
 },
 {
  "id": "H16",
  "name": "Price Drop / Deal Slam",
  "desc": "the strikethrough price, the new price and a % badge slam onto the product on frame 1.",
  "categories": "all, best during promotions (BFCM, Prime Day, 11.11).",
  "platforms": "TikTok (Shop), Meta DR, Shorts.",
  "emotion": "urgency, gain.",
  "keyframe": "the product hero, with price layers per E04.",
  "motion": "the old price appears, a strike line draws in 0.2 s, the new price slams from 2.0× to 1.0×, and a % badge rotates in.",
  "durationSec": [
   1.0,
   1.5
  ],
  "text": "`T-BADGE` \"−40%\" plus \"Today only\" (only if true)",
  "sfx": "`kaching` or `thump`. - Risk, **policy**: - The FTC (16 CFR 233) requires the struck price to be a bona fide former price, offered regularly for a reasonably substantial period [S22]. - TikTok requires the ad's discount to match the landing page [S8]. - Read live prices at render time and date-stamp the fine print.",
  "risk": "",
  "aiFit": "high",
  "perf": "[A] Deals and Discounts are the #1 holiday content type that TikTok shoppers engage with (45%) [S6]. [C] Weak as an evergreen cold opener."
 },
 {
  "id": "H17",
  "name": "Creator Talking Head (UGC opener)",
  "desc": "a creator looks into the lens and delivers one line (\"Okay, I need to talk about this ___\") with the product in hand.",
  "categories": "beauty, apps, supplements (compliant claims only), fashion, gadgets.",
  "platforms": "TikTok (Spark), Reels.",
  "emotion": "trust, parasocial connection.",
  "keyframe": "chest-up framing, the face in the upper BODY_BAND, the product held at chin height.",
  "motion": "a real creator clip is preferred. If AI, use a lip-synced avatar only if quality passes QC.",
  "durationSec": [
   1.5,
   3.0
  ],
  "text": "`T-NATIVE` auto-captions",
  "sfx": ": VO only, music ducked −12 dB.",
  "risk": "**high** for AI. Lip-sync and identity drift [S27], and an AI person needs disclosure [S8][S26]. Fake \"real customer\" framing is deceptive.",
  "aiFit": "low",
  "perf": "[A] TikTok data reports Spark Ads (creator posts) with 134% higher completion and 157% higher 6-s view-through rate than standard in-feed ads, via inBeat [S7]. TikTok recommends featuring people [S1][S2]."
 },
 {
  "id": "H18",
  "name": "Green-Screen Reaction",
  "desc": "a creator is keyed over a product page, review, headline or comment and points at it.",
  "categories": "viral products, apps, deals, \"dupes\".",
  "platforms": "TikTok-native, Reels.",
  "emotion": "social proof, curiosity.",
  "keyframe": "a background screenshot (the product page or 5-star reviews) at full frame. The creator cut-out sits in the lower-left 45% of the BODY_BAND.",
  "motion": "the background scrolls slowly (y −200 over 2 s). The creator points, and a highlight box draws around the claim.",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "`T-NATIVE`",
  "sfx": ": VO.",
  "risk": "background reviews must be real and attributable. The AI creator has the same risks as H17. Readable UI screenshots must be real assets, never AI-rendered text.",
  "aiFit": "med",
  "perf": "[B] Green-screen reaction is described as \"extremely native\" and performing well on TikTok [S29], and listed as a reliable visual hook [S17]."
 },
 {
  "id": "H19",
  "name": "Stop-Motion Assembly",
  "desc": "components jump into place frame by frame (12 fps) and build the product, a meal or a set.",
  "categories": "bundles, kits, modular gear, food, stationery, toys.",
  "platforms": "Reels, TikTok.",
  "emotion": "playful delight, craft.",
  "keyframe": "a flat-lay of parts. Generate 8–12 still positions by moving the cut-out layers, and render at 12 fps (`fps=12`, hold 2 frames). - DUR 1.2–2.0 s. TXT: one word per jump (`T-POP`). SFX `click` or `pop` on every frame jump, quantised to the beat.",
  "motion": "",
  "durationSec": [
   1.2,
   2.0
  ],
  "text": ": one word per jump (`T-POP`)",
  "sfx": "`click` or `pop` on every frame jump, quantised to the beat.",
  "risk": "very low. It is all compositing from official cut-outs.",
  "aiFit": "high",
  "perf": "[B] Motion's 2026 trend research finds crafted, human-visible motion styles stand out against smooth AI polish [S18]. [C] Otherwise practitioner pattern."
 },
 {
  "id": "H20",
  "name": "Scale Contrast",
  "desc": "the product next to an unexpected reference object (\"this projector is smaller than a soda can\"), or tiny-to-huge.",
  "categories": "compact electronics, portable gear, large TVs, power banks, cameras (Insta360).",
  "platforms": "all.",
  "emotion": "surprise, disbelief.",
  "keyframe": "the product and a known object side by side at correct relative scale (measure from spec sheets).",
  "motion": "the camera pulls from the reference object to the product, or the product grows from palm-size to wall-size via a scale animation.",
  "durationSec": [
   1.2,
   2.0
  ],
  "text": "`T-STACK` \"Smaller than ___\"",
  "sfx": "`whoosh` and a `pop`.",
  "risk": "wrong relative scale is a misleading claim. AI scale inconsistencies.",
  "aiFit": "high",
  "perf": "[A, principle] Surprise gave 1.7× VTR [S1]. [C] Format pattern."
 },
 {
  "id": "H21",
  "name": "\"Things TikTok Made Me Buy\" / Haul",
  "desc": "trend-native text over a quick 3–4 product montage. Your product is the hero, or it is the \"#1\".",
  "categories": "home gadgets, beauty, kitchen, car accessories, viral DTC.",
  "platforms": "TikTok (organic-native), Reels.",
  "emotion": "FOMO, social belonging.",
  "keyframe": "the product in a lived-in home setting, lo-fi grade (slight grain, natural light).",
  "motion": "0.5 s cuts on beats with handheld shake.",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "`T-NATIVE` \"Things TikTok made me buy that are actually worth it\"",
  "sfx": ": trending-style music (licensed CML).",
  "risk": "an implied endorsement by TikTok, and showing other brands' products. Use your own catalog only. The phrase is a trend meme, so check market fit and how fatigued it is.",
  "aiFit": "med",
  "perf": "[A] 77% of TikTok users like it when brands use trends, memes or challenges [S1]. [B] Lo-fi shop videos outperform studio productions (vendor claim, about 3×) [S32]. Treat it as a hypothesis."
 },
 {
  "id": "H22",
  "name": "Torture Test (drop, water, sun-glare, weight)",
  "desc": "the product survives an extreme test on frame 1: dropped, submerged, set on fire, stood on, or set against a sun-glare test for screens.",
  "categories": "phone cases, cameras (Insta360), cycling gear (Rockbros), outdoor, bags, cookware, anti-glare TVs and monitors, car mounts.",
  "platforms": "TikTok, Shorts, Reels.",
  "emotion": "tension, then proof.",
  "keyframe": "the product mid-fall or mid-splash (the keyframe must be mid-motion).",
  "motion": "a 0.5× slow-motion impact, then a 1× check shot (\"still works\").",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "`T-STACK` \"Dropped it from 2 m.\" then \"Still perfect.\"",
  "sfx": ": crash or splash `foley` plus a `thump`.",
  "risk": "**misleading-claim risk if simulated**. An AI-generated survival is not evidence. Use real test footage, or label it as a dramatisation and keep claims within certified ratings (IP68 etc.) [S8]. Physics artefacts.",
  "aiFit": "low",
  "perf": "[B] Shock-factor demonstrations (example: the Tempur-Pedic wine-glass test) are a listed visual hook [S17]. Demonstration hooks are strongest for physical products [S16]."
 },
 {
  "id": "H23",
  "name": "Lifestyle Moment",
  "desc": "an aspirational slice of life (a morning-coffee window seat, a mountain-bike ridge, a cosy movie night) with the product naturally in frame.",
  "categories": "home, outdoor and cycling, fashion and jewellery, TVs (movie night), cars.",
  "platforms": "Meta (brand), Reels, Shorts.",
  "emotion": "aspiration, belonging.",
  "keyframe": "a wide or medium environment with the product at ≥ 25% of the frame area in the BODY_BAND. Golden-hour grade.",
  "motion": "slow dolly-in or drone-style descent (the \"cinematic wide\" hook).",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "`T-STACK` with an identity line (\"Sunday mornings, upgraded.\")",
  "sfx": ": ambient bed plus a music swell.",
  "risk": "low thumb-stop for cold DR. The product gets lost, so enforce the 25% area rule. Faces in wide shots are acceptable for AI.",
  "aiFit": "high",
  "perf": "[A] Relatable slice-of-life scenes with ordinary people gave 1.5× purchase intent for brand ads [S3]. [B] The cinematic wide shot is a listed visual hook [S17]."
 },
 {
  "id": "H24",
  "name": "Seasonal / Holiday Surprise",
  "desc": "a seasonal icon (snow globe, pumpkin, fireworks, heart box) cracks open or transforms into the product.",
  "categories": "gifting, any promo window.",
  "platforms": "TikTok, Reels in season.",
  "emotion": "delight, festive nostalgia.",
  "keyframe": "a seasonal object on a festive plate.",
  "motion": "an AI transformation (globe shakes, snow clears, the product is inside) or a compositing match-cut, then H04 push.",
  "durationSec": [
   1.5,
   2.0
  ],
  "text": "`T-STACK` \"Your Black Friday surprise 🎁\" plus the live % off",
  "sfx": ": bells or `pop`.",
  "risk": "morph artefacts during the transformation. Seasonal claims (delivery-by dates) must be true.",
  "aiFit": "med",
  "perf": "[A] Holiday playbook: Deals 45%, Reviews 44%, Tutorials 38%, Unboxings 28% engagement among holiday shoppers [S6]. Surprise gave 1.7× VTR [S1]. ### Interface- and native-format family"
 },
 {
  "id": "H25",
  "name": "Search-Bar / Typing Hook",
  "desc": "a search field types \"best ___ for ___\", then the product appears as the \"result\".",
  "categories": "apps, electronics, considered purchases, B2C services.",
  "platforms": "TikTok, Reels.",
  "emotion": "relatability (I searched that too).",
  "keyframe": "a generic (not Google-branded) rounded search bar `T-UI` at y 400–520 over a blurred product plate.",
  "motion": "typewriter at 18–22 chars/s, then the bar slides up and the product slams in (H04).",
  "durationSec": [
   1.2,
   2.0
  ],
  "text": "",
  "sfx": "`keys` clacks, then a `pop`.",
  "risk": "do not imitate a real search engine's trade dress, or functional UI [S9].",
  "aiFit": "high",
  "perf": "[B] Typing-effect and search-bar hooks are listed as consistently performing visual hooks, and keystroke sound adds an ASMR element [S17]."
 },
 {
  "id": "H26",
  "name": "Comment-Reply Hook",
  "desc": "a comment bubble (\"Does it actually fit a 65\" TV?\") floats on screen, then the answer clip plays.",
  "categories": "all, best for objection handling (retargeting).",
  "platforms": "TikTok-native, Reels.",
  "emotion": "curiosity, social proof.",
  "keyframe": "a `T-UI` comment bubble at y 320–480 (avatar circle plus 2 lines) over the product scene.",
  "motion": "the bubble scales 0.9→1.0 with a `pop`, then a push into the answer shot.",
  "durationSec": [
   1.0,
   1.5
  ],
  "text": "",
  "sfx": "`pop`.",
  "risk": "the comment must be real (paraphrase a real customer question) and must not use TikTok's exact reply-sticker UI as a deceptive element.",
  "aiFit": "high",
  "perf": "[B] The comment-box hook is listed as blending into feeds while adding social proof [S17]."
 },
 {
  "id": "H27",
  "name": "Chat / Text-Message Hook",
  "desc": "a message thread (\"babe what do you want for xmas\" \"THIS 👇\") reveals the product.",
  "categories": "gifting, fashion and jewellery, couples' products, apps.",
  "platforms": "TikTok, Reels.",
  "emotion": "intimacy, humour.",
  "keyframe": "2–3 chat bubbles `T-UI` stacked at y 320–900 over a blurred plate.",
  "motion": "bubbles pop in on beats, and the last bubble contains the product image, which expands to full frame.",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "",
  "sfx": ": soft `pop` per bubble. Avoid copying the OS's exact message sound.",
  "risk": "mimicking OS notifications is \"non-existent functionality\" on Meta [S9]. Keep it stylised, never a lock-screen notification.",
  "aiFit": "high",
  "perf": "[B] Chat-conversation and incoming-call hooks are listed visual hooks [S17]. Avoid the incoming-call variant because of the notification policy."
 },
 {
  "id": "H28",
  "name": "Pattern Interrupt (\"Stop scrolling\")",
  "desc": "a sudden visual break: the product slaps into frame, a colour flash, a hand blocks the lens, or a freeze frame with a record-scratch.",
  "categories": "all, best for low-awareness impulse buys.",
  "platforms": "TikTok, Reels.",
  "emotion": "startle.",
  "keyframe": "a solid brand-colour frame or a hand over the lens.",
  "motion": "within 0.3 s the product enters from off-screen with an overshoot, plus a 2-frame white flash (`fade` or `eq=brightness`).",
  "durationSec": [
   0.5,
   1.0
  ],
  "text": ": 2–3 words, 120 px",
  "sfx": "`scratch` or `thump`.",
  "risk": "the epilepsy-safe flash limit is ≤ 3 flashes/s. Being purely attention-grabbing can attract low-intent viewers. Motion warns that high-hook ads may not convert [S17b].",
  "aiFit": "high",
  "perf": "[B] Physical motion plus text in the first 2 s is reported to give up to +50% 3-s retention versus static openings (secondary source) [S19]. A 20% thumb-stop with real intent outperforms a 50% viral hook [S16]."
 },
 {
  "id": "H29",
  "name": "Side-by-Side Comparison (us vs. generic)",
  "desc": "two products in a split screen face the same test, and ours wins.",
  "categories": "electronics (brightness, sound), appliances (crispiness, noise), cleaning, outdoor gear.",
  "platforms": "Meta, TikTok, Shorts.",
  "emotion": "competitive judgment.",
  "keyframe": "a split screen with the left side labelled \"Other\" (unbranded) and the right side ours.",
  "motion": "the same action on both sides at once, and the losing side desaturates.",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": ": labels plus a verdict `T-STACK`",
  "sfx": ": a buzzer on the left, `chime` on the right.",
  "risk": "comparative-advertising rules. Never show or name a real competitor without substantiation. AI-simulated results are not evidence [S8].",
  "aiFit": "med",
  "perf": "[C] Practitioner pattern. [A, principle] Contrast and early product proof [S3]."
 },
 {
  "id": "H30",
  "name": "Myth-Bust / Contrarian Claim",
  "desc": "\"Stop buying ___ (common practice)\" or \"You've been using ___ wrong\", then the product is the right way.",
  "categories": "kitchen, skincare (compliant), cycling and fitness accessories, apps.",
  "platforms": "TikTok, Reels.",
  "emotion": "provocation, curiosity.",
  "keyframe": "the \"wrong\" practice with a red ✕ stamp animation.",
  "motion": "the stamp slams in (scale 1.4→1.0), then a whip to the product.",
  "durationSec": [
   1.2,
   2.0
  ],
  "text": "`T-STACK`",
  "sfx": ": buzzer `thump`, then `whoosh`.",
  "risk": "works on skeptical, experienced audiences and less on general consumers [S16]. Claims must be substantiated.",
  "aiFit": "high",
  "perf": "[B] Contrarian opinion hooks are listed with the fit noted [S16]."
 },
 {
  "id": "H31",
  "name": "Hands-Only Demo (first-frame action)",
  "desc": "the product is already working on frame 1: a button pressed, a mount clicking in, a lid snapping. No intro.",
  "categories": "car accessories (Ottocast adapters), kitchen gadgets, tools, cameras, cycling lights.",
  "platforms": "all.",
  "emotion": "competence, \"I want that convenience\".",
  "keyframe": "mid-action, with hands partially framed and the product dominant.",
  "motion": "AI image-to-video of the single action (≤ 2 s) or real footage. Cut on the action completing.",
  "durationSec": [
   1.0,
   2.0
  ],
  "text": "`T-STACK` \"Plug in. Done.\"",
  "sfx": "`click` `foley` exactly on the action.",
  "risk": "AI hands. Product UI on screens (CarPlay screens) must be composited, never generated.",
  "aiFit": "med",
  "perf": "[B] Demonstration is strongest for physical products (\"show the product working in the first frame\") [S16]."
 },
 {
  "id": "H32",
  "name": "Ranking / Countdown Reveal (\"#1 will surprise you\")",
  "desc": "a ranked list counts down to our product as #1.",
  "categories": "catalogs, categories with comparisons, gift guides.",
  "platforms": "TikTok, Shorts.",
  "emotion": "suspense.",
  "keyframe": "a `T-BADGE` \"#3\"→\"#2\"→\"#1\" on beats with quick product flashes (your own SKUs only). The #1 reveal gets an H04 push. DUR 1.5–2.5 s. SFX: `click`s, then a `riser` into the #1.",
  "motion": "",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "",
  "sfx": ": `click`s, then a `riser` into the #1.",
  "risk": "curiosity gaps can get high 3-s views but poor watch-through if the payoff underdelivers [S16].",
  "aiFit": "high",
  "perf": "[A] Suspense early in a story gave +16% watch time [S1]."
 },
 {
  "id": "H33",
  "name": "Split-Screen Duet / Stitch Reaction",
  "desc": "the top half is a \"viral\" clip or problem, and the bottom half is the creator or product response.",
  "categories": "viral products, gadgets, food.",
  "platforms": "TikTok-native, Reels.",
  "emotion": "curiosity, social conversation.",
  "keyframe": "two stacked 1080×960 panels. The top panel plays the setup clip, and the bottom panel shows the product reaction. The divider line sits at y 960. DUR 1.5–2.5 s. TXT `T-NATIVE` on the bottom panel. SFX: original audio from the top clip, then VO.",
  "motion": "",
  "durationSec": [
   1.5,
   2.5
  ],
  "text": "`T-NATIVE` on the bottom panel",
  "sfx": ": original audio from the top clip, then VO.",
  "risk": "you need rights to the stitched clip. Use your own or licensed footage only.",
  "aiFit": "med",
  "perf": "[A] Trends and native formats [S1]. [C] Otherwise."
 },
 {
  "id": "H34",
  "name": "Cinematic Wide → Hero Drop",
  "desc": "an epic establishing shot (city at dusk, mountain road, living-room wall), then a hard push to the product.",
  "categories": "TVs and projectors, cars and car tech, outdoor, premium home.",
  "platforms": "Meta, Shorts, CTV cut-downs.",
  "emotion": "awe, scale.",
  "keyframe": "an AI-generated wide shot (High AI-fit, no faces) at 1.0 s with a slow push, then a whip-zoom (`zoompan` z 1→3 in 0.25 s plus `whoosh`) to the official product composite. TXT: the logo after the drop. SFX: atmospheric bed, `whoosh`, `thump`.",
  "motion": "",
  "durationSec": [
   1.0,
   2.0
  ],
  "text": ": the logo after the drop",
  "sfx": ": atmospheric bed, `whoosh`, `thump`.",
  "risk": "frame 1 must be bright and readable. Generic AI landscapes look stock.",
  "aiFit": "high",
  "perf": "[B] The cinematic wide shot is a listed hook for a premium aesthetic and sense of scale [S17]."
 },
 {
  "id": "H35",
  "name": "Slow-Motion Splash / Pour / Drop-In",
  "desc": "the product drops into water, sauce is poured, or powder bursts in high-speed slow motion.",
  "categories": "beverages, food, kitchen appliances, skincare, waterproof gear.",
  "platforms": "Reels, Meta, TikTok.",
  "emotion": "sensory appetite, freshness.",
  "keyframe": "an AI-generated splash around a composited product (keep the product layer from the official photo above the splash, and mask the splash over the bottom edge). 0.25× speed via `minterpolate`. DUR 1.2–2.0 s. TXT: minimal. SFX: splash `foley` plus a `thump`.",
  "motion": "",
  "durationSec": [
   1.2,
   2.0
  ],
  "text": ": minimal",
  "sfx": ": splash `foley` plus a `thump`.",
  "risk": "liquid physics artefacts, and edges where the splash meets the product. Food styling must reflect the real product.",
  "aiFit": "med",
  "perf": "[B] Slow motion is listed as a reliable visual hook for texture and sensory products [S17]."
 }
] as Omit<HookDef, "family" | "frameOneProduct">[];
