/* eslint-disable */
// GENERATED by scripts from out/research/ad-research (2026-10-06). Edit the research, then regenerate.
import type { PlatformProfile } from "./types";

export const PLATFORM_PROFILES: PlatformProfile[] = [
 {
  "platform": "tiktok",
  "placements": [
   "in_feed",
   "spark_ads",
   "topview_lite"
  ],
  "audience": {
   "ageCore": "18-34",
   "genderSkew": "female-leaning (W42%/M30% of US adults)",
   "mindset": "entertainment-led discovery; impulse + TikTok Shop",
   "tone": "native, lo-fi, creator-led, playful, trend-aware"
  },
  "aspect": "9:16",
  "canvas": [
   1080,
   1920
  ],
  "durationSec": {
   "ideal": 21,
   "range": [
    15,
    34
   ],
   "max": 60
  },
  "hookSec": 3,
  "cutsPerSec": {
   "first6s": 0.8,
   "body": 0.5
  },
  "soundMode": "on",
  "styleTags": [
   "ugc",
   "talking-head",
   "pov",
   "unboxing",
   "problem-solution-demo",
   "trend-format",
   "break-4th-wall",
   "handheld"
  ],
  "captionStyle": "native TikTok-style white bold with black stroke, 2-5 words per chunk, centered upper-middle, plus burned-in speech captions",
  "voiceTone": "casual first-person creator, conversational, upbeat, Gen Z/millennial slang allowed",
  "musicStyle": "trending-style track from Commercial Music Library, >120 BPM, beat-synced cuts",
  "ctaStyle": "short personal verbal CTA + TikTok CTA card in last 2-3s ('Grab yours, link below')",
  "branding": "product on screen by 3s; logo subtle (on product/pack), no opening logo slate",
  "safeZone": {
   "top": 160,
   "bottom": 480,
   "left": 64,
   "right": 140
  },
  "policy": [
   "AIGC label if synthetic people/voice",
   "commercial-content toggle for creator content",
   "CML music only"
  ],
  "doNots": [
   "TV-commercial polish",
   "opening logo/brand slate",
   "horizontal or letterboxed video",
   "silent video",
   "text in bottom 480px or right rail",
   "unlicensed trending sound",
   "AI avatar posing as a real customer testimonial",
   "slow intro before product appears"
  ],
  "id": "tiktok"
 },
 {
  "platform": "instagram",
  "placements": [
   "reels"
  ],
  "audience": {
   "ageCore": "18-34",
   "genderSkew": "female (W55%/M44%)",
   "mindset": "aesthetic lifestyle discovery",
   "tone": "aspirational, curated, polished-native"
  },
  "aspect": "9:16",
  "canvas": [
   1080,
   1920
  ],
  "durationSec": {
   "ideal": 15,
   "range": [
    9,
    30
   ],
   "max": 90
  },
  "hookSec": 2,
  "cutsPerSec": {
   "first6s": 0.7,
   "body": 0.5
  },
  "soundMode": "on",
  "styleTags": [
   "creator-lifestyle",
   "aesthetic-broll",
   "transformation",
   "grwm",
   "product-in-life",
   "human-presence",
   "text-sticker-hook"
  ],
  "captionStyle": "clean sans-serif sticker text (rounded label bg), brand-palette accents, auto-captions for VO",
  "voiceTone": "warm, confident creator or ASMR-light; polished but personal",
  "musicStyle": "on-trend aesthetic pop/lo-fi/house from Meta Sound Collection, beat-matched",
  "ctaStyle": "soft in-frame CTA ('Shop the look', 'Tap Shop Now') above bottom 35%; Meta CTA button",
  "branding": "organic early branding inside safe zone; logo small top-left or on product",
  "safeZone": {
   "top": 269,
   "bottom": 672,
   "left": 65,
   "right": 65
  },
  "policy": [
   "AI info label for photorealistic synthetic",
   "Paid Partnership label for creators",
   "no personal-attribute copy"
  ],
  "doNots": [
   "anything in bottom 35%",
   "cheap/harsh look",
   "landscape reuse",
   "hard-sell discount shouting",
   "over 30s without a reason",
   "personal-attribute claims ('your acne')"
  ],
  "id": "instagram_reels"
 },
 {
  "platform": "instagram",
  "placements": [
   "stories"
  ],
  "audience": {
   "ageCore": "18-44",
   "genderSkew": "female",
   "mindset": "quick tap-through, friends' now",
   "tone": "casual, intimate"
  },
  "aspect": "9:16",
  "canvas": [
   1080,
   1920
  ],
  "durationSec": {
   "ideal": 10,
   "range": [
    6,
    15
   ],
   "max": 60
  },
  "hookSec": 1.5,
  "cutsPerSec": {
   "first6s": 0.6,
   "body": 0.4
  },
  "soundMode": "mixed",
  "styleTags": [
   "card-sequence",
   "sticker-text",
   "selfie",
   "product-closeup"
  ],
  "captionStyle": "Stories sticker/label text, large, max 6 words per card",
  "voiceTone": "friendly direct address",
  "musicStyle": "light background track; message must survive mute",
  "ctaStyle": "'Tap to shop ↑' sticker above bottom 20%",
  "branding": "brand + product by 3s",
  "safeZone": {
   "top": 269,
   "bottom": 384,
   "left": 65,
   "right": 65
  },
  "doNots": [
   "more than one idea per 5s card",
   "small text",
   "audio-dependent message"
  ],
  "id": "instagram_stories"
 },
 {
  "platform": "meta_feed",
  "placements": [
   "facebook_feed",
   "instagram_feed"
  ],
  "audience": {
   "ageCore": "30-64",
   "genderSkew": "female (FB W78%/M63%)",
   "mindset": "value, deals, practical problem-solving; Marketplace habits",
   "tone": "clear, trustworthy, value-forward"
  },
  "aspect": "4:5",
  "canvas": [
   1080,
   1350
  ],
  "durationSec": {
   "ideal": 15,
   "range": [
    6,
    30
   ],
   "max": 60
  },
  "hookSec": 3,
  "cutsPerSec": {
   "first6s": 0.5,
   "body": 0.35
  },
  "soundMode": "off",
  "styleTags": [
   "demo",
   "benefit-callouts",
   "offer-led",
   "social-proof",
   "before-after-(non-body)",
   "comparison"
  ],
  "captionStyle": "burned-in captions mandatory; big bold headline bar top; price/offer badge; >=64px type",
  "voiceTone": "friendly explainer, plain language (optional—must work muted)",
  "musicStyle": "unobtrusive background; no sudden loud audio",
  "ctaStyle": "explicit 'Shop now / Get the deal' + price/offer frame in last 3s; Meta CTA button",
  "branding": "logo + product + core message within 3s",
  "safeZone": {
   "top": 60,
   "bottom": 120,
   "left": 54,
   "right": 54
  },
  "doNots": [
   "sound-dependent storytelling",
   "tiny text",
   "slow cinematic open",
   "more than 1 offer",
   "unsubstantiated 'lowest price'",
   "personal-attribute copy"
  ],
  "id": "meta_feed"
 },
 {
  "platform": "facebook",
  "placements": [
   "reels"
  ],
  "audience": {
   "ageCore": "25-54",
   "genderSkew": "female",
   "mindset": "entertainment + deals",
   "tone": "native, value-forward"
  },
  "aspect": "9:16",
  "canvas": [
   1080,
   1920
  ],
  "durationSec": {
   "ideal": 15,
   "range": [
    9,
    30
   ],
   "max": 60
  },
  "hookSec": 2,
  "cutsPerSec": {
   "first6s": 0.6,
   "body": 0.45
  },
  "soundMode": "on",
  "styleTags": [
   "demo",
   "creator-review",
   "offer-led",
   "human-presence"
  ],
  "captionStyle": "sticker text + captions, larger than IG",
  "voiceTone": "friendly reviewer, clear",
  "musicStyle": "upbeat mainstream",
  "ctaStyle": "offer + 'Shop now' above bottom 35%",
  "branding": "early",
  "safeZone": {
   "top": 269,
   "bottom": 672,
   "left": 65,
   "right": 65
  },
  "doNots": [
   "Gen Z slang overload",
   "anything in bottom 35%",
   "silent"
  ],
  "id": "facebook_reels"
 },
 {
  "platform": "youtube",
  "placements": [
   "instream_skippable"
  ],
  "audience": {
   "ageCore": "18-64",
   "genderSkew": "balanced (M86%/W83%)",
   "mindset": "research/search intent, lean-back, often on TV",
   "tone": "informative, credible, review-style"
  },
  "aspect": "16:9",
  "canvas": [
   1920,
   1080
  ],
  "durationSec": {
   "ideal": 20,
   "range": [
    15,
    60
   ],
   "max": 180
  },
  "hookSec": 5,
  "cutsPerSec": {
   "first6s": 0.4,
   "body": 0.3
  },
  "soundMode": "on",
  "styleTags": [
   "abcd",
   "problem-demo-proof",
   "reviewer",
   "feature-showcase",
   "comparison",
   "testimonial-real-only"
  ],
  "captionStyle": "lower-third key-benefit titles, large TV-legible type; optional subtitles",
  "voiceTone": "confident warm narrator or expert reviewer; brand name spoken in first 5s",
  "musicStyle": "cinematic/modern bed under VO, ducked",
  "ctaStyle": "CTA repeated in VO + graphics; end screen with product, offer, QR code for CTV",
  "branding": "brand visual + audio mention within 5s, recurring",
  "safeZone": {
   "top": 60,
   "bottom": 200,
   "left": 80,
   "right": 400
  },
  "doNots": [
   "delayed brand reveal",
   "slow logo intro",
   "text near bottom-right skip button",
   "tiny text (TV viewing)",
   "relying on click-only CTA"
  ],
  "id": "youtube_instream_skippable"
 },
 {
  "platform": "youtube",
  "placements": [
   "instream_nonskippable_15s"
  ],
  "audience": {
   "ageCore": "18-64",
   "genderSkew": "balanced",
   "mindset": "lean-back, captive",
   "tone": "polished, single-message"
  },
  "aspect": "16:9",
  "canvas": [
   1920,
   1080
  ],
  "durationSec": {
   "ideal": 15,
   "range": [
    7,
    15
   ],
   "max": 15
  },
  "hookSec": 2,
  "cutsPerSec": {
   "first6s": 0.5,
   "body": 0.4
  },
  "soundMode": "on",
  "styleTags": [
   "mini-arc",
   "hero-product",
   "single-benefit"
  ],
  "captionStyle": "one headline + one proof line, TV-legible",
  "voiceTone": "brand narrator",
  "musicStyle": "branded/upbeat bed",
  "ctaStyle": "brand + CTA end frame (last 3s)",
  "branding": "open and close on brand",
  "safeZone": {
   "top": 60,
   "bottom": 200,
   "left": 80,
   "right": 200
  },
  "doNots": [
   "multiple messages",
   "UGC chaos",
   "ending without brand"
  ],
  "id": "youtube_instream_nonskippable_15s"
 },
 {
  "platform": "youtube",
  "placements": [
   "bumper_6s"
  ],
  "audience": {
   "ageCore": "18-64",
   "genderSkew": "balanced",
   "mindset": "reach/recall",
   "tone": "punchy"
  },
  "aspect": "16:9",
  "canvas": [
   1920,
   1080
  ],
  "durationSec": {
   "ideal": 6,
   "range": [
    5,
    6
   ],
   "max": 6
  },
  "hookSec": 1,
  "cutsPerSec": {
   "first6s": 0.7,
   "body": 0.7
  },
  "soundMode": "on",
  "styleTags": [
   "one-message",
   "hero-shot",
   "visual-gag",
   "sequencing"
  ],
  "captionStyle": "max 5 words on screen",
  "voiceTone": "one spoken line or none",
  "musicStyle": "sonic logo / sting",
  "ctaStyle": "brand lock-up last 1s",
  "branding": "logo+product by 1s and held",
  "safeZone": {
   "top": 60,
   "bottom": 200,
   "left": 80,
   "right": 200
  },
  "doNots": [
   "cut-down of a long ad",
   "more than one message",
   "small product"
  ],
  "id": "youtube_bumper_6s"
 },
 {
  "platform": "youtube",
  "placements": [
   "shorts"
  ],
  "audience": {
   "ageCore": "13-34",
   "genderSkew": "balanced/male-leaning",
   "mindset": "quick entertainment, instant swipe",
   "tone": "authentic, upbeat, creator-like"
  },
  "aspect": "9:16",
  "canvas": [
   1080,
   1920
  ],
  "durationSec": {
   "ideal": 20,
   "range": [
    10,
    35
   ],
   "max": 60
  },
  "hookSec": 1.5,
  "cutsPerSec": {
   "first6s": 0.8,
   "body": 0.5
  },
  "soundMode": "on",
  "styleTags": [
   "creator-to-camera",
   "everyday-person",
   "demo",
   "fun",
   "shareable"
  ],
  "captionStyle": "bold creator captions upper-middle",
  "voiceTone": "casual direct address, energetic",
  "musicStyle": "upbeat, plus VO (sound = +20% conversions)",
  "ctaStyle": "verbal + on-screen CTA from 3s aligned with Shorts CTA button",
  "branding": "early but organic",
  "safeZone": {
   "top": 241,
   "bottom": 480,
   "left": 60,
   "right": 201
  },
  "doNots": [
   "re-cropped 16:9 TV ad",
   "silent",
   "slow open",
   "text under right action rail"
  ],
  "id": "youtube_shorts"
 },
 {
  "platform": "google",
  "placements": [
   "demand_gen",
   "performance_max"
  ],
  "audience": {
   "ageCore": "18-64",
   "genderSkew": "balanced",
   "mindset": "discovery→conversion across YouTube, Shorts, Discover, Gmail",
   "tone": "product-centric, clear"
  },
  "aspect": [
   "16:9",
   "1:1",
   "9:16",
   "4:5"
  ],
  "canvas": [
   [
    1920,
    1080
   ],
   [
    1080,
    1080
   ],
   [
    1080,
    1920
   ],
   [
    1080,
    1350
   ]
  ],
  "durationSec": {
   "ideal": 15,
   "range": [
    10,
    30
   ],
   "max": 60
  },
  "hookSec": 3,
  "cutsPerSec": {
   "first6s": 0.5,
   "body": 0.4
  },
  "soundMode": "mixed",
  "styleTags": [
   "abcd",
   "product-demo",
   "offer",
   "feed-ready"
  ],
  "captionStyle": "burned-in captions + benefit titles (Discover/Gmail are muted)",
  "voiceTone": "clear narrator; CTA spoken",
  "musicStyle": "neutral upbeat bed",
  "ctaStyle": "CTA repeated in VO and overlay; end card with offer",
  "branding": "within 5s",
  "assetRules": {
   "perAspectMin": 3,
   "minSec": 10,
   "productFeed": true
  },
  "safeZone": {
   "top": 0,
   "bottom": 0,
   "left": 0,
   "right": 0,
   "note": "use per-surface zones: Shorts profile for 9:16, in-stream profile for 16:9"
  },
  "doNots": [
   "single aspect only",
   "under 10s",
   "letting Google auto-generate video",
   "sound-only message"
  ],
  "id": "google_demand_gen"
 },
 {
  "platform": "pinterest",
  "placements": [
   "standard_video",
   "max_width",
   "premiere_spotlight"
  ],
  "audience": {
   "ageCore": "18-44 (Gen Z >50% globally)",
   "genderSkew": "~70% female ad audience",
   "mindset": "planning, search, ideas, gifting",
   "tone": "inspirational, calm, useful"
  },
  "aspect": "9:16",
  "canvas": [
   1080,
   1920
  ],
  "durationSec": {
   "ideal": 10,
   "range": [
    6,
    15
   ],
   "max": 60
  },
  "hookSec": 2.5,
  "cutsPerSec": {
   "first6s": 0.4,
   "body": 0.3
  },
  "soundMode": "off",
  "styleTags": [
   "how-to",
   "idea-list",
   "styled-flatlay",
   "home/beauty/gift",
   "seasonal"
  ],
  "captionStyle": "elegant headline text, idea framing ('3 ways to…'), stays legible as still cover",
  "voiceTone": "none or soft",
  "musicStyle": "soft optional",
  "ctaStyle": "soft ('Save this idea', 'Shop the look')",
  "branding": "logo/product in first few seconds",
  "safeZone": {
   "top": 270,
   "bottom": 790,
   "left": 65,
   "right": 195
  },
  "doNots": [
   "hard-sell shouting",
   "audio-dependent",
   "text below y=1130",
   "dark/negative tone"
  ],
  "id": "pinterest"
 },
 {
  "platform": "snapchat",
  "placements": [
   "single_video",
   "commercials"
  ],
  "audience": {
   "ageCore": "13-24",
   "genderSkew": "slightly female (~55% ad audience)",
   "mindset": "camera-first social, fast",
   "tone": "raw, playful, selfie"
  },
  "aspect": "9:16",
  "canvas": [
   1080,
   1920
  ],
  "durationSec": {
   "ideal": 6,
   "range": [
    3,
    10
   ],
   "max": 30
  },
  "hookSec": 1.5,
  "cutsPerSec": {
   "first6s": 1.0,
   "body": 0.8
  },
  "soundMode": "on",
  "styleTags": [
   "selfie",
   "ugc",
   "bold-motion",
   "single-idea"
  ],
  "captionStyle": "Snap-style caption bar, few words",
  "voiceTone": "Gen Z casual",
  "musicStyle": "trend-style, punchy",
  "ctaStyle": "'Swipe up' style above bottom 250px",
  "branding": "brand/product by 2s",
  "safeZone": {
   "top": 150,
   "bottom": 250,
   "left": 40,
   "right": 40
  },
  "doNots": [
   "horizontal TV spot",
   "long story",
   "logo in top 150px",
   "polished brand film"
  ],
  "id": "snapchat"
 }
] as PlatformProfile[];
